### ISSUE TITLE
DigitalReadOut.qml: How to toggle between Relative and Machine Position Offset?

### ISSUE THREAD

**Issue by yishinli** [machinekoder/QtQuickVcp#71]
In [DigitalReadOut.qml](https://github.com/strahlex/QtQuickVcp/blob/master/src/applicationcontrols/DigitalReadOut.qml), we may display either Relative Position or Machine Position, based on applicationCore.status.config.positionOffset. However, I have no idea how to toggle the value of applicationCore.status.config.positionOffset, for switching DRO between Relative and Machine Position.
The only way I can do is setting the [DISPLAY]POSITION_OFFSET of INI file for either RELATIVE or MACHINE position.

Please advise the correct approach if I would like to toggle the Relative/Machine position of DRO?

**Comment by strahlex** [comment]
Yes, changing the INI value is the only option so far.

However, it would be possible to add a new settings variable: https://github.com/strahlex/QtQuickVcp/blob/master/src/application/ApplicationSettings.qml#L49
Which can be toggled like https://github.com/strahlex/Cetus/blob/master/Cetus/ApplicationMenuBar.qml#L86

If it is just for a personal UI project you can of course also directly set QML property to what you prefer.
